services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8002:8000"

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: poetry run alembic upgrade head
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:17.6-trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    ports:
      - "8004:80"

volumes:
  data:
