name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
      JWT_EXPIRATION_MINUTES: ${{ secrets.JWT_EXPIRATION_MINUTES}}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v6

      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Executar testes
        run: poetry run task test
